### ISSUE TITLE
error when converting to JSON

### ISSUE THREAD

**Issue by pfoster** [cashierfu/CashierFu#3]
in the playground for the datakit adjustments and attachments are giving me an error I don't understand when I run the toJsonString() method.

**Comment by acwright** [comment]
Crap... I just fixed some of this... and didn't pull first... now we have a conflict... working on it

**Comment by acwright** [comment]
Ok. Pull experimental branch. Hopefully I fixed some stuff related to Alamofire and playgrounds.

**Comment by pfoster** [comment]
I'm still getting the error in the playground

**Comment by pfoster** [comment]
I just pushed it up

**Comment by acwright** [comment]
Is this because of prettyPrinted: true? I made it false again and it showed up like I was expecting in the playground...

**Comment by acwright** [comment]
Ok. Forget my last message... I just saw the error you are getting... I'm working on it now.

**Comment by acwright** [comment]
Reference to the problem: http://stackoverflow.com/questions/25503830/valueforkey-throws-error-for-optional-value-swift

**Comment by acwright** [comment]
Here is the lowdown:

I am using key-value coding functions of NSObject to do the "meta" programming necessary in CFKObject to serialize and deserialize the models to and from dictionaries. In order for this to work though I need to call: valueForKey("key_name") on the object. This is great and all until you have a model with a property that is an Int or Bool type in which case it gets pissed because these types can't be converted to NSNumber automatically by the compiler like the String -> NSString conversion. So from what I can tell we need to make our models Int and Bool properties into NSNumber types and it works again. Check the playground out.

**Comment by pfoster** [comment]
I updated all of those. Do the doubles need to change too?

**Comment by acwright** [comment]
Yep. And this may just be a temp workaround. I'm looking at other solutions that would not need NS classes
